# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

type -fp lsb_release >/dev/null 2>&1 && export IS_LINUX=YES || IS_LINUX=
[[ -z $IS_LINUX ]] && echo 'lsb_release is not installed'

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac


# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
export HISTSIZE=1000
export HISTFILESIZE=2000
# don't put duplicate lines or lines starting with space in the history.
# To also ignore lines starting with space, use ignoreboth.
# See bash(1) for more options
export HISTCONTROL=ignoredups

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

# ANSI color codes
RS="\[\033[0m\]"    # reset
HC="\[\033[1m\]"    # hicolor
UL="\[\033[4m\]"    # underline
INV="\[\033[7m\]"   # inverse background and foreground
FBLK="\[\033[30m\]" # foreground black
FRED="\[\033[31m\]" # foreground red
FGRN="\[\033[32m\]" # foreground green
FYEL="\[\033[33m\]" # foreground yellow
FBLE="\[\033[34m\]" # foreground blue
FMAG="\[\033[35m\]" # foreground magenta
FCYN="\[\033[36m\]" # foreground cyan
FWHT="\[\033[37m\]" # foreground white
BBLK="\[\033[40m\]" # background black
BRED="\[\033[41m\]" # background red
BGRN="\[\033[42m\]" # background green
BYEL="\[\033[43m\]" # background yellow
BBLE="\[\033[44m\]" # background blue
BMAG="\[\033[45m\]" # background magenta
BCYN="\[\033[46m\]" # background cyan
BWHT="\[\033[47m\]" # background white
FHRD="\[\033[01;31m\]" # foreground hicolor red
FHGR="\[\033[01;32m\]" # foreground hicolor green
FHYE="\[\033[01;33m\]" # foreground hicolor yellow
FHBL="\[\033[01;34m\]" # foreground hicolor blue
FHMA="\[\033[01;35m\]" # foreground hicolor magenta
FHCY="\[\033[01;36m\]" # foreground hicolor cyan

# Look up key codes using infocmp (from ncurses)
# Check keycodes for the terminal with the bash "read" command

if [ "$color_prompt" = yes ]; then
#    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
    PS1="${debian_chroot:+($debian_chroot)}$FHGR\u$RS:$FHCY\w$FHYE\$ $RS"
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

echo 'Executing .bashrc'

# Rebind stop-terminal from the default ^S to ^X to enable bash history ^S
# for incremental forward search.
# start-terminal is still ^Q.
stty stop ^X

[[ -n $IS_LINUX ]] && lsb_release -a
uname -a
echo
type -fp inxi >/dev/null 2>&1 && inxi -Sr

export DISTRO=
if [[ -n $IS_LINUX ]]; then
    export DISTRO=`lsb_release -i | sed 's/^.*:\s//' | tr "[:upper:]" "[:lower:]"`
fi

MACHINE_SPECIFIC=`[[ $DISTRO == "ubuntu" ]] && echo /home/robinschaufler/bashrcLib/oracleUbuntu.bash`
if [[ -n $MACHINE_SPECIFIC && -f $MACHINE_SPECIFIC ]]; then
    . $MACHINE_SPECIFIC
fi

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

ALIASFILE=/home/robinschaufler/bashrcLib/aliases.bash
if [[ -f $ALIASFILE ]]; then
    . $ALIASFILE
fi
